import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/footer";
import TopHeader from "@/components/layouts/header/TopHeader";
import MiddleHeader from "@/components/layouts/header/MiddleHeader";
import MainHeader from "@/components/layouts/header/MainHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div>
          <header className="bg-primary text-white p-4 w-full">
            <TopHeader />
          </header>
          <div className="">
            <main className="px-10">
              <div className="grid grid-cols-12 gap-6 w-full">
                <div className="col-span-3 w-full"></div>
                <div className="col-span-9 w-full">
                  <MiddleHeader />
                  <MainHeader />
                </div>
              </div>
              <div>{children}</div>
            </main>
          </div>
          <footer className="bg-primary text-white mt-4 w-full">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
